### Смиирнов Николай M3303, Коняхин Всеволод M3305
### Методы оптимизации. LU-Разложение

In [1]:
import numpy as np
import pandas as pd

from scipy.sparse import csr_matrix, dok_matrix, lil_matrix

### Имплементация

In [2]:
from methods import get_LU, solve_system, get_inverse
from sparse_methods import get_LU_sparse, solve_system_sparse, get_inverse_sparse

### LU Decomposition-test

In [3]:
A = np.array([
    [1, 2, 3, 1, 2, 1], 
    [0, 1, 0, 6, -1, 0], 
    [2, 3, 1, -1, -2, -1], 
    [7, 2, 6, 0, 2, 11], 
    [1, 0, -2, 1, 4, 3], 
    [1, -5, 3, -4, 2, 0], 
])

L1, U1 = get_LU(A)

In [4]:
pd.DataFrame(L1)

0     1    2         3         4    5
0  1.0   0.0  0.0  0.000000  0.000000  0.0
1  0.0   1.0  0.0  0.000000  0.000000  0.0
2  2.0  -1.0  1.0  0.000000  0.000000  0.0
3  7.0 -12.0  3.0  1.000000  0.000000  0.0
4  1.0  -2.0  1.0  0.160714  1.000000  0.0
5  1.0  -7.0 -0.0  0.660714 -0.670644  1.0

In [5]:
pd.DataFrame(U1)

0    1    2     3         4          5
0  1.0  2.0  3.0   1.0  2.000000   1.000000
1  0.0  1.0  0.0   6.0 -1.000000   0.000000
2  0.0  0.0 -5.0   3.0 -7.000000  -3.000000
3  0.0  0.0  0.0  56.0 -3.000000  13.000000
4  0.0  0.0  0.0   0.0  7.482143   2.910714
5  0.0  0.0  0.0   0.0  0.000000  -7.637232

In [6]:
L1 @ U1

array([[ 1.,  2.,  3.,  1.,  2.,  1.],
       [ 0.,  1.,  0.,  6., -1.,  0.],
       [ 2.,  3.,  1., -1., -2., -1.],
       [ 7.,  2.,  6.,  0.,  2., 11.],
       [ 1.,  0., -2.,  1.,  4.,  3.],
       [ 1., -5.,  3., -4.,  2.,  0.]])

### LU Decomposition-test Sparse

In [7]:
L2, U2 = get_LU_sparse(csr_matrix(A))

In [8]:
pd.DataFrame(L2.todense())

0     1    2         3         4    5
0  1.0   0.0  0.0  0.000000  0.000000  0.0
1  0.0   1.0  0.0  0.000000  0.000000  0.0
2  2.0  -1.0  1.0  0.000000  0.000000  0.0
3  7.0 -12.0  3.0  1.000000  0.000000  0.0
4  1.0  -2.0  1.0  0.160714  1.000000  0.0
5  1.0  -7.0  0.0  0.660714 -0.670644  1.0

In [9]:
pd.DataFrame(U2.todense())

0    1    2     3         4          5
0  1.0  2.0  3.0   1.0  2.000000   1.000000
1  0.0  1.0  0.0   6.0 -1.000000   0.000000
2  0.0  0.0 -5.0   3.0 -7.000000  -3.000000
3  0.0  0.0  0.0  56.0 -3.000000  13.000000
4  0.0  0.0  0.0   0.0  7.482143   2.910714
5  0.0  0.0  0.0   0.0  0.000000  -7.637232

In [10]:
L2.todense() @ U2.todense()

matrix([[ 1.,  2.,  3.,  1.,  2.,  1.],
        [ 0.,  1.,  0.,  6., -1.,  0.],
        [ 2.,  3.,  1., -1., -2., -1.],
        [ 7.,  2.,  6.,  0.,  2., 11.],
        [ 1.,  0., -2.,  1.,  4.,  3.],
        [ 1., -5.,  3., -4.,  2.,  0.]])

### Решение СЛАУ

In [11]:
A = np.array([
    [1, -1, 3, 1], 
    [4, -1, 5, 4],
    [2, -2, 4, 1],
    [1, -4, 5, -1]
])

b = np.array([5, 4, 6, 3])
gt_solution = np.array([9, 18, 10, -16])

In [12]:
solve_system(A, b)

array([  9.,  18.,  10., -16.])

In [13]:
solve_system_sparse(A, b).todense()

matrix([[  9.],
        [ 18.],
        [ 10.],
        [-16.]])

#### Random matrix

In [14]:
A_rand = np.random.rand(6, 6) * 10000
b_rand = np.random.rand(6) * 10000

In [15]:
b_rand

array([3539.77086852, 6664.13647486,  112.50033922,  494.23143706,
       5443.26171297, 2996.50191931])

In [16]:
x1 = solve_system(A_rand, b_rand)
x1

array([ 4.50804286, -3.12469556, -0.26224487,  1.46475111,  1.36559649,
       -1.20248095])

In [17]:
A_rand @ x1

array([3539.77086852, 6664.13647486,  112.50033922,  494.23143706,
       5443.26171297, 2996.50191931])

In [18]:
x2 = solve_system_sparse(A_rand, b_rand)
x2.todense()

matrix([[ 4.50804286],
        [-3.12469556],
        [-0.26224487],
        [ 1.46475111],
        [ 1.36559649],
        [-1.20248095]])

In [19]:
A_rand @ x2.todense()

matrix([[3539.77086852],
        [6664.13647486],
        [ 112.50033922],
        [ 494.23143706],
        [5443.26171297],
        [2996.50191931]])

### Inverse Matrix search

In [20]:
A = np.array([
    [2, 1, 1, 0],
    [3, 2, 0, 0],
    [1, 1, 3, 4],
    [2, -1, 2, 3]
])

In [21]:
A_inverse_1 = get_inverse(A)
A_inverse_1

array([[ 0.0625 ,  0.1875 , -0.1875 ,  0.25   ],
       [-0.09375,  0.21875,  0.28125, -0.375  ],
       [ 0.96875, -0.59375,  0.09375, -0.125  ],
       [-0.71875,  0.34375,  0.15625,  0.125  ]])

In [22]:
A @ A_inverse_1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
A_inverse_2 = get_inverse_sparse(A)
A_inverse_2.todense()

matrix([[ 0.0625 ,  0.1875 , -0.1875 ,  0.25   ],
        [-0.09375,  0.21875,  0.28125, -0.375  ],
        [ 0.96875, -0.59375,  0.09375, -0.125  ],
        [-0.71875,  0.34375,  0.15625,  0.125  ]])

In [27]:
A @ A_inverse_2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Task 3. Matrix generation based on `k`

In [24]:
def generate_eye_matrix(k):
    matrix = np.zeros((k, k))
    
    values_set = [0, -1, -2, -3, -4] 
    
    for i in range(k):
        for j in range(k):
            if i != j:
                matrix[i, j] = np.random.choice(values_set)
                
    for i in range(k):
        matrix[i, i] = matrix[i, :].sum()
        
    if np.random.rand(1)[0] > 0.5:
        matrix[i, i] += 10 ** (-k)
                
    return matrix


def conduct_experiment(k, num_exp):
    solutions = list()
    errors = list()
    
    x = np.arange(k) + 1
    
    for i in range(num_exp):
        A = generate_eye_matrix(k)
        
        


### Task 4. Gilbert matrix generation based on `k`

In [25]:
def generate_gilbert_matrix(k):
    matrix = np.zeros((k, k))
    
    for i in range(k):
        for j in range(k):
            matrix[i, j] = 1 / ((i+1) + (j+1) - 1)
            
    return matrix